### ISSUE TITLE
Connection denied when going back from authentication

### ISSUE THREAD

**Issue by K1ngmar** [K1ngmar/Transcendence#43]
# Issue
When trying to log in with (intra, discord or github) and not authenticating with them (say you decided that you dont want to log in with github) and you go back, you get connection denied where 'retry' does not work and `disconnect other tab` gets 2 forbidden requests
<img width="949" alt="Screen Shot 2022-04-19 at 11 29 55 AM" src="https://user-images.githubusercontent.com/57956359/163974219-ed2e7bb1-84b0-4e88-91a1-92705375e01e.png">

# info
It only happens when you are already authenticated with another service and are trying to add a new one
when going back from the authentication tab the frontend returns `AUTHENTICATED` state while the backend returns `OAUTH` 

# environment
- chrome

Refreshing the tab does fix it

**Comment by mraasvel** [comment]
Fixed it, it was a chrome caching issue as usual.
