### ISSUE TITLE
Bad request for avatar

### ISSUE THREAD

**Issue by K1ngmar** [K1ngmar/Transcendence#44]
# BUG
When logged in and then trying to log in on another tab/window, pressing  the `disconnect other tab` button will result in a bad api call.
<img width="753" alt="Screen Shot 2022-04-19 at 11 55 08 AM" src="https://user-images.githubusercontent.com/57956359/163978843-27060812-42ee-46ce-abab-10c663043693.png">

it happens on both `chrome` and `firefox` (havent tested it on any other browsers)

**Comment by mraasvel** [comment]
fixed in another branch
